config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :dogs
# root "dogs#show"
root "walkers#index"
resources :walkers
  # get "walkers" => "walkers#index"
  # get "walkers/:id" => "walkers#show", as: :walker

# root "dog#show"

# resources :valleys
  # root "dinosaurs#index"

  # resources :dinosaurs


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord

belongs_to :walker

  def self.order_by_name
    order(:dog_name)
  end

  def new
      @dog = Dog.new
  end

  def edit
    @dog = Dog.find(params[:id])
  end
end

app/models/walker.rb
class Walker < ApplicationRecord

  has_many :dogs

  def self.order_by_name
    order(:walker_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def show
    @dogs = Dog.all
  end

  def create
    @walker = Walker.find(params[:walker_id])
    @dog = @walker.dogs.build(dog_params)

    if @dog.save
      redirect_to @walker
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    redirect_to @walker
  end

  private
  def dog_params
    params.require( :dog ).permit( :dog_name, :owner_name, :dog_size )
  end
end

app/controllers/walkers_controller.rb
class WalkersController < ApplicationController

  def index
    @walkers = Walker.all
  end

  def show
    @walker = Walker.find(params[:id])
    @dog = Dog.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/walkers_helper.rb
module WalkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogwalking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <br><br>
    <hr>

    <%= link_to "[All Walkers]", root_path %>

  </body>
</html>

app/views/walkers/_form.html.erb
<%= form_for @dog do |d| %>
    <%= d.label :dog_name %>
    <%= d.text_field :dog_name %>

    <%= d.label :owner_name %>
    <%= d.text_field :owner_name %>

    <%= d.label :dog_size %>
    <%= d.text_field :dog_size %>

    <%= hidden_field_tag :walker_id, @walker.id, { :walker_id => @walker.id }%>

    <%= d.submit (@dog.new_record? ? "Create" : "Update") %>
<% end %>

app/views/walkers/index.html.erb
<!DOCTYPE html>
  <html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link type="css/text" rel="stylesheet" href="/app/assets/stylesheets/application.css">
  <title>The Dog Walkers</title>
</head>
<body class="homepage">
  <img class="banner" src="http://www.barkdenver.com/files/5714/2126/5232/s5810nb9g6pio7lr.jpg" alt="Welcome">

  <h1 class="header1">The Dog Walkers</h1>

  <h2 class="header2"> Welcome to our service</h2>
  <p class="choosewalker">Please choose one of our walkers</p>
<div class="walker">
  <% @walkers.each do |walker| %>
    <p class="walker_name"> <%= link_to walker.walker_name, walker_path(walker.id) %></p>
  <% end %>
  </div>


</body>
</html>

app/views/walkers/new.html.erb
<h2>New Dog</h2>

<%= form_for @dog do |d| %>
    <%= d.label :dog_name %>
    <%= d.text_field :dog_name %>

    <%= d.label :owner_name %>
    <%= d.number_field :owner_name %>

    <%= d.label :dog_size %>
    <%= d.text_field :dog_size %>

    <%= d.submit "Create" %>
<% end %>

app/views/walkers/show.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link type="css/text" rel="stylesheet" href="/app/assets/stylesheets/application.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body class="homepage">


<h1 class="header1"><%= @walker.walker_name %></h1>
<div class="walkerimg"><%= image_tag @walker.walker_img %>
<p class="choosewalker">Hi, I am <%= @walker.walker_name %> and I am your <%= @walker.walker_time %> walker</p>


<h2 class="header2">Do you want me to walk your dog?</h2>
<p> please register your dog below</p>
<div class="walker">
<%= form_for @dog do |d| %>
    <%= d.label :dog_name %>
    <%= d.text_field :dog_name %>

    <%= d.label :owner_name %>
    <%= d.text_field :owner_name %>

    <%= d.label :dog_size %>
    <%= d.text_field :dog_size %>

    <%= hidden_field_tag :walker_id, @walker.id, { :walker_id => @walker.id }%>

    <%= d.submit (@dog.new_record? ? "Create" : "Update") %>
<% end %>

</div>

<h4>Dogs I am walking today</h4>

<% if @walker.dogs.any? %>
  <ul>
    <% @walker.dogs.each do |dog| %>
      <li><%= dog.dog_name %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no dogs who walk with this walker.</p>
<% end %>

</div>
<%= link_to 'Back', walkers_path %>


</body>
</html>